### ISSUE TITLE
Generate an existing Belgian BIC 

### ISSUE THREAD

**Issue by ThomasVerhoeven1998** [philipdeherdt/numbers-at-hand#33]
Beflius = GKCCBEBB
KBC = KREDBEBB
BNP = GEBABEBB
ING = BBRUBEBB
Argenta = ARSPBE22
Beobank = CTBKBEBX
AXA = AXABBE22
Crelan = NICABEBB

**Comment by philipdeherdt** [comment]
Functionality added in release 1.9
